### ISSUE TITLE
Some problem about the config/formal 

### ISSUE THREAD

**Issue by HalloBC** [Tencent/TH_COVID19_International#3]
After importing the data and installing the dependencies perfectly, I can‘t continue executing the step five , because there is no file folder named formal in config. I don't know how to deal with this problem, because I am new to this project， but I want to quote it，  need help T-T

**Comment by lightxue** [comment]
Please redo step 2, that'll be fine.
> 2. Modify the configuration file under `/config/formal`, referring to the sample of  `/config/test`

**Comment by HalloBC** [comment]
> Please redo step 2, that'll be fine.
> 
> > 1. Modify the configuration file under `/config/formal`, referring to the sample of  `/config/test`

But there is no file named formal in the filefolder config.

**Comment by lightxue** [comment]
`/config/formal` is a folder for configuration files. It'll work if rename `/config/test` to `/config/formal`.
