### ISSUE TITLE
Export Path in self-traige README is incorrect

### ISSUE THREAD

**Issue by pjayathissa** [Tencent/TH_COVID19_International#6]
https://github.com/Tencent/TH_COVID19_International/tree/master/src/servers/COVID-19-self-triage

In `Basic Usage`. the python path configuration should be `export PYTHONPATH = .`. Otherwise, you are already in the server directory and cannot `import server.modules`

**Comment by lnisre** [comment]
thanks for you reply, I will change the README.

**Comment by laishzh** [comment]
@pjayathissa We have just updated the README, please check it. If you have any further question, feel free to contact us.
