### ISSUE TITLE
In Chinese version translation is not finished, partially English

### ISSUE THREAD

**Issue by huiling123** [Tencent/TH_COVID19_International#7]
![image](https://user-images.githubusercontent.com/57208442/78207592-b5310980-74d4-11ea-8691-de576b569e3f.png)

**Comment by SophiaWoo** [comment]
The language switch is just for the static web. Since the API does not support multiple languages yet, the part in English you pointed out actually depends on the data in your database.

**Comment by huiling123** [comment]
Received with many thanks.


-----原始邮件-----
发件人:SophiaWoo <notifications@github.com>
发送时间:2020-04-05 16:39:22 (星期日)
收件人: Tencent/TH_COVID19_International <TH_COVID19_International@noreply.github.com>
抄送: Huiling <lihuiling@teleinfo.cn>, Author <author@noreply.github.com>
主题: Re: [Tencent/TH_COVID19_International] In Chinese version translation is not finished, partially English (#7)






The language switch is just for the static web. Since the API does not support multiple languages yet, the part in English you pointed out actually depends on the data in your database.
