### ISSUE TITLE
getInfoBatch 接口中getForeignHistory 数据问题

### ISSUE THREAD

**Issue by Meteor1216** [Tencent/TH_COVID19_International#8]
getInfoBatch 接口中getForeignHistory  这个历史数据从30号开始几乎平缓，感觉与国外数据进程不太符合，请问这里是数据有什么问题了么？

**Comment by foolish-code** [comment]
这个开源项目主要是开源了产品形态和相关的实现代码 ，对于疫情数据仅用于demo，不会持续 维护 ，请谅解
