### ISSUE TITLE
A cookie associated with a cross-site resource at http://qq.com/ was set without the `SameSite` attribute

### ISSUE THREAD

**Issue by bulolo** [Tencent/TH_COVID19_International#9]
![image](https://user-images.githubusercontent.com/10026498/78387280-a3a14c00-7611-11ea-86a9-5d9dec9719da.png)

请问部署的时候遇到这个问题该如何解决

**Comment by SophiaWoo** [comment]
'A cookie associated with ...' 告警是Chrome对即将更新的版本关于cookie支持状况的一个说明。原项目运营为了实现cookie共享而为domain指定了二级域名，建议您部署时根据自身实际情况修改这一配置。感谢您对该项目的关注！
